# Baseline Model Configuration
# ============================

data:
  languages: ["eng", "deu", "ptbr"]
  emotions: ["joy", "sadness", "fear", "anger", "surprise", "disgust"]
  test_size: 0.2
  random_state: 42

feature_extraction:
  method: "tfidf"  # or "count"
  max_features: 10000
  ngram_range: [1, 2]
  lowercase: true
  strip_accents: "unicode"
  stop_words: null  # Don't use for multilingual

models:
  naive_bayes:
    enabled: true
    alpha: 1.0
  
  logistic_regression:
    enabled: true
    max_iter: 1000
    random_state: 42
    C: 1.0
  
  svm:
    enabled: true
    kernel: "linear"
    probability: true
    random_state: 42
    C: 1.0
  
  random_forest:
    enabled: true
    n_estimators: 100
    random_state: 42
    max_depth: null

evaluation:
  metrics: ["f1_macro", "f1_micro", "f1_per_emotion"]
  cross_lingual: true
  save_predictions: true

output:
  save_models: true
  save_results: true
  results_dir: "./results/baseline_results"